// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using core_web_api.Data;

#nullable disable

namespace core_web_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230911051734_Department")]
    partial class Department
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("core_web_api.Models.Domain.Employee", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("emp_mail_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("emp_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("emp_ph_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
